{{- if .Values.config.token -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "admiral-server.secretName" . }}
  labels:
    {{- include "admiral-server.labels" . | nindent 4 }}
data:
  token: {{ .Values.config.token |  b64enc }}
type: Opaque
{{- end }}

